.github/workflows/docker-deploy.yml
.gitignore
Dockerfile
build.gradle
src/main/resources/application.properties
src/main/resources/templates/home.html

- close #1 
- AWS 세팅 (EC2, RDS, S3)
- 의존성 추가(MySQL, QueryDSL, JPA, S3)
- CI/CD 적용 (Dockerfile, Github Workflow)
- application.properties 파일 gitignore에 추가(보안상 위험 때문에)
- Docker name, password나 중요한 정보들은 Github Secret으로 관리하도록 했습니다!
- AWS나 중요한 정보들 제 Notion에 일단 정리해두었는데, 개발자 공용 Notion 생기면 거기에 모두 넣어놓을게요!!
- discord 알림 CI는 오늘 밤이나 내일 중으로 적용하겠습니다! 바로 알바 갈 준비를 해야해서 ㅠㅠㅠㅠ
<br>

[chore #1] CI/CD 적용

---

build.gradle
src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
src/main/java/com/ongi/backend/domain/caregiver/dto/request/ValidateIdRequestDto.java
src/main/java/com/ongi/backend/domain/caregiver/exception/CaregiverErrorCase.java
src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java

- close #13 
> 요양보호사 아이디 중복 확인 API 구현

[feat #13] 요양보호사 아이디 중복 확인 API 구현

---

src/main/java/com/ongi/backend/common/aop/LoggingAspect.java

- close #22 
- 서비스 로깅 AOP 버그 수정

[fix #22] 서비스 로깅 AOP 버그 수정

---

build.gradle
src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
src/main/java/com/ongi/backend/domain/auth/dto/LoginTokensDto.java
src/main/java/com/ongi/backend/domain/auth/dto/request/CaregiverLoginRequest.java
src/main/java/com/ongi/backend/domain/auth/dto/response/CaregiverLoginResponse.java
src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
src/main/java/com/ongi/backend/domain/auth/entity/enums/UserType.java
src/main/java/com/ongi/backend/domain/auth/exception/AuthErrorCase.java
src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
src/main/java/com/ongi/backend/domain/caregiver/entity/enums/LicenseType.java
src/main/java/com/ongi/backend/domain/caregiver/exception/CaregiverErrorCase.java
src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java

- close #24 
- 요양보호사 로그인 구현
- 로그인 시 accessToken은 response body, refreshToken은 쿠키로 전송

[feat #24] 요양보호사 로그인 구현

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java
src/main/java/com/ongi/backend/common/config/SwaggerConfig.java
src/main/java/com/ongi/backend/common/security/CustomAccessDeniedHandler.java
src/main/java/com/ongi/backend/common/security/CustomAuthenticationEntryPoint.java
src/main/java/com/ongi/backend/common/security/JwtAuthorizationFilter.java
src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
src/main/java/com/ongi/backend/domain/auth/entity/enums/Authority.java
src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java

- close #26 
- jwt 인증, 인가 구현
- swagger에 토큰 헤더 설정

[feat #] jwt 인증, 인가 추가

---

src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java

[feat #28] 로그아웃 구현

---

src/main/java/com/ongi/backend/common/security/JwtTokenizer.java
src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
src/main/java/com/ongi/backend/domain/auth/entity/enums/Authority.java
src/main/java/com/ongi/backend/domain/auth/exception/AuthErrorCase.java
src/main/java/com/ongi/backend/domain/auth/repository/RefreshTokenRepository.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java

- close #31 
- 인증 토큰 재발급 로직 구현

[feat #31] 인증 토큰 재발급 로직 구현

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java
src/main/java/com/ongi/backend/common/security/CustomAccessDeniedHandler.java
src/main/java/com/ongi/backend/common/security/CustomAuthenticationEntryPoint.java
src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java

- close #36 
- 요양보호사 프로필 등록 권한 변경
- 인증/인가 오류 반환 형식 수정

[refactor #36] 인증/인가 수정

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java
src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
src/main/java/com/ongi/backend/domain/center/dto/request/CenterSearchCondition.java
src/main/java/com/ongi/backend/domain/center/exception/CenterErrorCase.java
src/main/java/com/ongi/backend/domain/center/service/CenterService.java

- 센터 조회 시 CenterSearchConditon을 통해 조회하도록 개선
- 센터 요청 관련 Security Filter 수정

[fix] center 관련 로직 수정

---

src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
src/main/java/com/ongi/backend/domain/caregiver/dto/request/CaregiverUpdateRequestDto.java
src/main/java/com/ongi/backend/domain/caregiver/dto/response/CaregiverResponseDto.java
src/main/java/com/ongi/backend/domain/caregiver/dto/response/InformationResponseDto.java
src/main/java/com/ongi/backend/domain/caregiver/dto/response/LicenseResponseDto.java
src/main/java/com/ongi/backend/domain/caregiver/dto/response/OptionalResponseDto.java
src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverInformation.java
src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverOptional.java
src/main/java/com/ongi/backend/domain/caregiver/repository/CaregiverRepository.java
src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java

- close #52 
- 요양보호사 마이페이지 api 구현

[feat #] 요양보호사 마이페이지 api 구현

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java
src/main/java/com/ongi/backend/common/security/JwtAuthorizationFilter.java
src/main/java/com/ongi/backend/domain/auth/entity/RefreshToken.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java
src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
src/main/java/com/ongi/backend/domain/senior/entity/Senior.java
src/main/java/com/ongi/backend/domain/senior/exception/SeniorErrorCase.java
src/main/java/com/ongi/backend/domain/senior/service/SeniorService.java

- close #43
- JWT 토큰에서 centerId를 추출하는 로직을 구현했습니다.
- 이제 특정 센터의 센터장, 복지사만이 센터에 어르신을 등록하고 조회할 수 있습니다.
- 어르신 몸무게 필드가 추가되었습니다.

[feat #43] JWT 토큰에서 centerId 추출해서 사용하는 로직 구현

---

src/main/java/com/ongi/backend/domain/senior/dto/request/SeniorRequestDto.java
src/main/java/com/ongi/backend/domain/senior/dto/response/SeniorResponseDto.java
src/main/java/com/ongi/backend/domain/senior/entity/Senior.java

[feat #55] 어르신 관리자 연락처 필드 추가

---

src/main/java/com/ongi/backend/common/config/LoggingFilterConfig.java
src/main/java/com/ongi/backend/common/config/SecurityConfig.java

- CloudWatch 연동 기능 추가
- CORS 설정 변경

[feat] CloudWatch 연동, CORS 설정 변경

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java

[fix] CORS 설정 변경

---

src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
src/main/java/com/ongi/backend/domain/senior/controller/SeniorController.java

- close #63 
- Controller의 응답값이 CommonResponse<Object>라고 되어 있어 응답 객체 형식을 명시하도록 수정

[fix #63] Controller의 응답값 수정

---

src/main/java/com/ongi/backend/domain/caregiver/entity/Caregiver.java
src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverInformation.java
src/main/java/com/ongi/backend/domain/caregiver/entity/CaregiverOptional.java
src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java

[fix] 요양보호사 회원가입 수정

---

src/main/java/com/ongi/backend/domain/auth/service/AuthService.java
src/main/java/com/ongi/backend/domain/caregiver/entity/enums/ToiletingAssistanceType.java

- close #68 
- 토큰 재발급, 배변 보조 타입 오류 수정

[fix] 토큰 재발급, 배변 보조 타입 오류 수정

---

src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
src/main/java/com/ongi/backend/domain/auth/service/AuthService.java

- close #71 
- 토큰 재발급, 로그인 인증 타입 오류 수정

[fix] 토큰 재발급, 로그인 인증 타입 오류 수정

---

src/main/java/com/ongi/backend/domain/caregiver/controller/CaregiverController.java
src/main/java/com/ongi/backend/domain/caregiver/dto/response/ProfileUrlResponseDto.java
src/main/java/com/ongi/backend/domain/caregiver/service/CaregiverService.java

- close #74 
- 요양보호사 프로필 링크 조회

[feat #74] 요양보호사 프로필 링크 조회

---

src/main/java/com/ongi/backend/common/config/SecurityConfig.java
src/main/java/com/ongi/backend/domain/center/controller/CenterController.java
src/main/java/com/ongi/backend/domain/center/dto/request/CenterEssentialRequestDto.java
src/main/java/com/ongi/backend/domain/center/dto/request/CenterOptionalRequestDto.java
src/main/java/com/ongi/backend/domain/center/dto/response/CenterEssentialResponseDto.java
src/main/java/com/ongi/backend/domain/center/dto/response/CenterOptionalResponseDto.java
src/main/java/com/ongi/backend/domain/center/dto/response/CenterProfileResponseDto.java
src/main/java/com/ongi/backend/domain/center/entity/Center.java
src/main/java/com/ongi/backend/domain/center/entity/enums/CenterGrade.java
src/main/java/com/ongi/backend/domain/center/exception/CenterErrorCase.java
src/main/java/com/ongi/backend/domain/center/service/CenterService.java

- close #73 
- 관리자 마이페이지 api 구현

[feat #73] 관리자 마이페이지 api 구현

---

src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java
src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java
src/main/java/com/ongi/backend/domain/matching/dto/response/LicenseResponseDto.java
src/main/java/com/ongi/backend/domain/matching/dto/response/MatchingCaregiverInfoResponseDto.java
src/main/java/com/ongi/backend/domain/matching/dto/response/WorkConditionResponseDto.java
src/main/java/com/ongi/backend/domain/matching/service/MatchingService.java

- close #84 
- 매칭된 요양보호사 정보 조회 구현

[feat] 매칭된 요양보호사 정보 조회 구현

---

src/main/java/com/ongi/backend/domain/matching/controller/CenterMatchingController.java

[hotfix] 매칭된 요양보호사 정보 조회 api 주소 수정

---

src/main/java/com/ongi/backend/domain/auth/controller/AuthController.java

[fix] ssl 오류 수정
